version: '3.1'

services:

    db:
      image: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: password
      volumes:
        - data:/data
    adminer:
      image: adminer
      restart: always
      ports:
        - 8081:8081

volumes:
    data: {}